### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by Kierst01** [UBC-MDS/passwordler#79]
- [x] We need to choose a license for our package, this should be done after Wednesday's class.

**Comment by mishelly-h** [comment]
I think MIT offers a light weight solution which allows the use if a copyright notice is provided. It is not optimized for contribution  which is okay, since we will not focus on further develop the package with a wider community. The MIT license allows the users to do almost anything with our package such as the usage, change and distribution.

**Comment by rorywhite200** [comment]
I agree, and looking at similar packages like [easy-password-generator 0.0.7 ](https://pypi.org/project/easy-password-generator/) they also use the MIT License. It seems like its standard practice and doesn't impose burdensome restrictions on people using the package.

**Comment by Kierst01** [comment]
I also agree with this, I don't think our package needs any restrictions. Should we add a short explanation to the readme? Or is having this issue here enough for marking purposes?

**Comment by zywkloo** [comment]
I considered a while about Apache 2.0. Then I realized Apache is stricter because it requires you to list all the modifications you make to the original software. In that case it would be harder for the further contributors.
